apiVersion: v1
kind: Secret
metadata:
  name: django-secrets
type: Opaque
data:
  # These are obviously not the real ones for production. Please NEVER commit production secrets to public repositories
  secretKey: X2UzbWtlMiFiaF8jKTUpPSl6OV8pdjQ9bT0pbyFyMTJwKiMyJkBqZ3YkLW92dXdfdHQK
  slackApiToken: eG94cC0zMzk3NjQ2Mzc3NjAtMzQwNTk3NTQ3MzE3LTM1ODI5NzAwNjkzMS0xMWYwNzNmNTc0OGZjZDQzZGQxNzRiNjkyZmMxNjdhMQ==
