env:
  browser: true
  es6: true
extends:
  - google
  - plugin:react/recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
settings:
  react:
    pragma: "React"
    version: detect
rules:
  require-jsdoc: 0
  react/prop-types: 0
  new-cap: 0
