env:
  browser: true
  es6: true
extends:
  - google
  - plugin:react/recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules:
  require-jsdoc: 0
  react/prop-types: 0
