sudo: false
language: python
python:
  - "3.6"
env:
  global:
    #environment variables for postgresql
    - PGHOST=localhost
    - PGPORT=5433
    - PGDATABASE=travis_ci
    - PGUSER=postgres
    - PGPASSWORD=giraffe
    #environment variables for application
    - POSTGRES_HOST=localhost
    - POSTGRES_PORT=5433
    - POSTGRES_DB=travis_ci
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=giraffe
    #python dir
    - PYTHONPATH=$TRAVIS_BUILD_DIR/app/
  matrix:
    #indicate different builds here
before_install:
  # chnge to 'test' soon
  # - export MODE=test
  - export MODE=development
  - mv .env.sample .env
  - source ./bin/init-environment.bash
install:
  - pip install -r requirements/test.txt
  - npm install
before_script:
  - psql -c 'create database travis_ci;' -U postgres --no-password
  - bash ./bin/init-node.bash
  - bash ./bin/init-django.bash
script:
  - bash ./bin/run-tests.bash
  - npm run coala
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
