sudo: false
language: python
python:
  - 3.6
env:
  global:
    # environment variables for postgresql
    - PGHOST=localhost
    - PGPORT=5433
    - PGUSER=postgres
    - PGPASSWORD=giraffe
    # environment variables for application
    - POSTGRES_DB=travis_ci
    - POSTGRES_HOST=localhost
    - POSTGRES_PORT=5433
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=giraffe
    # app settings
    - PYTHONPATH=$TRAVIS_BUILD_DIR/app/
    #TODO change MODE to 'test'
    - MODE=test
    - NODE_ENV=test
  matrix:
    # indicate different builds here
before_install:
  # make sure postgres is initialised
  - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
  - sudo service postgresql restart
  - sleep 1
install:
  - source ./backend/bin/init-environment.bash
  - source ./frontend/bin/init-environment.bash
  - pip install -r ./backend/requirements/test.txt
  - cd frontend || exit; npm install
before_script:
  # Only works without password if PGPASSWORD is set
  - psql -c 'create database travis_ci;' -U postgres --no-password
  - bash ./bin/init-node.bash
  - bash ./bin/compile_sass.bash
  - bash ./bin/init-django.bash
script:
  - bash ./bin/run-tests.bash
  - docker-compose run --rm coala
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
