sudo: false
language: python
python:
  - "3.6"
services:
  - docker
env:
  - PYTHONPATH="$TRAVIS_BUILD_DIR/app/"
before_install:
  - docker pull timvanmourik/giraffe-tools
install:
  - npm install
  - pip install -r requirements/test.txt
before_script:
  - cd app;
  - python manage.py collectstatic --noinput -i other
  - python manage.py migrate
script:
  - coverage run ./manage.py test --noinput --settings=app.settings.local
  - cd ..; npm test
after_success:
  - pip install codecov
  - codecov
  - bash <(curl -s https://codecov.io/bash) -cF javascript
