sudo: false
language: python
python:
  - "3.6"
env:
  global:
    - PGPORT=5433
    - POSTGRES_PORT=5433
    - POSTGRES_DB=travis_ci
    - POSTGRES_HOST=localhost
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=""
  # These are the separate environments to test:
  - PYTHONPATH=$TRAVIS_BUILD_DIR/app/
before_install:
  # chnge to 'test' soon
  # - export MODE=test
  - export MODE=development
  - mv .env.sample .env
  - source ./bin/init-environment.bash
install:
  - pip install -r requirements/test.txt
  - npm install
before_script:
  - psql -c 'create database travis_ci;' -U postgres
  - bash ./bin/init-node.bash
  - bash ./bin/init-django.bash
script:
  - bash ./bin/run-tests.bash
  - npm run coala
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
