sudo: false
language: python
python:
  - "3.6"
env:
  - PYTHONPATH="$TRAVIS_BUILD_DIR/app/"
install:
  - npm install
  - pip install -r requirements/test.txt
before_script:
  - cd app; python manage.py collectstatic --noinput -i other &
script:
  - cd app; pytest
after_success:
  - pip install codecov
  - codecov
