sudo: false
language: python
python:
  - "3.6"
services:
  - postgresql
env:
  # Rather than specifying different environment variables, this specifies
  # different environments as a whole
  - PYTHONPATH=$TRAVIS_BUILD_DIR/app/ POSTGRES_DB=travis_ci POSTGRES_HOST=localhost POSTGRES_PORT="" POSTGRES_USER=postgres POSTGRES_PASSWORD=""
before_install:
  # chnge to 'test' soon
  # - export MODE=test
  - export MODE=development
  - mv .env.sample .env
  - source ./bin/init-environment.bash
install:
  - pip install -r requirements/test.txt
  - npm install
before_script:
  - psql -c 'create database travis_ci;' -U postgres
  - bash ./bin/init-node.bash
  - bash ./bin/init-django.bash
script:
  - bash ./bin/run-tests.bash
  - npm run coala
