sudo: false
language: python
python:
  - "3.6"
services:
  - docker
env:
  # Rather than specifying different environment variables, this specifies
  # different environments as a whole
  - PYTHONPATH="$TRAVIS_BUILD_DIR/app/";
before_install:
  - export MODE=production
  - mv .env.sample .env
  - source ./bin/init-environment.bash
install:
  - pip install -r requirements/test.txt
  - npm install
before_script:
  - bash ./bin/init-node.bash
  - bash ./bin/init-django.bash
script:
  - bash ./bin/run-tests.bash
  - npm run coala
