sudo: false
language: python
python:
  - "3.6"
services:
  - docker
env:
  - PYTHONPATH="$TRAVIS_BUILD_DIR/app/"
  - MODE='production'
before_install:
  - docker pull timvanmourik/giraffe-tools
install:
  - export $(cat .env.sample | grep -v ^# | xargs)
  - export MODE=production
  - npm install
  - pip install -r requirements/test.txt
before_script:
  - cd app;
  - python manage.py collectstatic --noinput -i other
  - python manage.py migrate
script:
  - python manage.py test
  - cd ..;
  - npm test
after_success:
  - pip install codecov
  - codecov
