sudo: false
language: python
python:
  - "3.6"
env:
  - PYTHONPATH="$TRAVIS_BUILD_DIR/app/"
install:
  - pip install -r requirements.txt
script:
  - pytest
after_success:
  - pip install codecov
  - codecov
