sudo: false
language: python
python:
  - 3.6
env:
  global:
    # environment variables for postgresql
    - PGHOST=localhost
    - PGPORT=5433
    - PGUSER=postgres
    - PGPASSWORD=giraffe
    # environment variables for application
    - POSTGRES_DB=travis_ci
    - POSTGRES_HOST=localhost
    - POSTGRES_PORT=5433
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=giraffe
    # app settings
    - PYTHONPATH=$TRAVIS_BUILD_DIR/app/
    #TODO change MODE to 'test'
    - DEBUG=False
    - NODE_ENV=test
    - WEBPACK_FOLDER_DJANGO=./assets/webpack_bundles
    - WEBPACK_FOLDER_NODE=../../backend/assets/webpack_bundles
  matrix:
    # indicate different builds here
before_install:
  # make sure postgres is initialised
  - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
  - sudo service postgresql restart
  - sleep 1
install:
  - pip install -r ./backend/requirements/test.txt
  - bash ./bin/post_compile
  - bash .heroku/run.sh
  - npm run heroku-prebuild
  - npm install
  - npm run heroku-postbuild
before_script:
  # Only works without password if PGPASSWORD is set
  - psql -c 'create database travis_ci;' -U postgres --no-password
  - bash ./test/init-tests.bash
script:
  - bash ./test/run-tests.bash
  - docker-compose run --rm coala
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
