version: '3'

services:
  web:
    build: .
    image: timvanmourik/giraffe-tools
    volumes:
      - .:/code
      - /tmp/.X11-unix:/tmp/.X11-unix # for GUI application
    command: bash bin/docker-command.bash
    ports:
      - "8000:8000"   # application server
      - "3000:3000"   # webpack hot reload server
      - "35729:35729" # django live reload server
