version: '3'

services:
  web:
    environment:
      - CHOKIDAR_USEPOLLING=true # for hot reloading on Windows
    build: .
    image: timvanmourik/giraffe-tools
    volumes:
      - .:/code
    command: bash bin/docker-command.bash
    ports:
      - "8000:8000"   # application server
      - "3000:3000"   # webpack hot reload server
      - "35729:35729" # django live reload server

  # coala is the 'linter', checking coding standard consistency
  coala:
    image: nemaniarjun/coala-docker-updated
    command: coala
    working_dir: /code
    volumes:
      - .:/code
      # this may not work on windows, need to think of a workaround
      # this will speed up multiple runs by a LOT
      - /tmp/coala:/cache