version: '3'

services:
  nginx:
    build: ./nginx
    ports:
      - "8000:8000"
    volumes:
      - ./public:/www/public/
    depends_on:
      - backend
    volumes:
      - ./nginx/config:/etc/nginx/conf.d
      - ./backend:/code
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://0.0.0.0:8000"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3

  backend:
    env_file:
      - ./backend/.env.sample
    environment:
      - CHOKIDAR_USEPOLLING=true # for hot reloading on Windows
    build: ./backend
    image: timvanmourik/giraffe-tools
    volumes:
      - ./backend:/code
      - webpack_bundles:/webpack
    command: ./bin/docker-command.bash
    ports:
      - "35729:35729"   # django live reload server
    expose:
      - "8000"
    depends_on:
      - database
      - frontend

  redis:
    # restart: unless-stopped
    image: redis:4.0-alpine
    volumes:
      - redis:/data
    ports:
      - "6379:6379"

  database:
    env_file:
      - ./database/.env.sample
    restart: unless-stopped
    build: ./database
    volumes:
      # This saves the database to a persistent volume:
      - postgres:/var/lib/postgresql/data
      # You could also save it locally to the `database` directory...
      # - ./database:/var/lib/postgresql/data
      # if ever we want to initialise the database
      # - ./demo.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      #TODO only works without quotes here, not sure why
      - 5432   # database port

  frontend:
    env_file:
      - ./frontend/.env.sample
    environment:
      - CHOKIDAR_USEPOLLING=true # for hot reloading on Windows
    build: ./frontend
    volumes:
      - ./frontend:/react
      - webpack_bundles:/bundles
    ports:
      - "3000:3000"
    command: ./bin/docker-command.bash


  # worker:
  #   build: ./worker
  #
  # rabbitmq:
  #   build: ./rabbitmq
  #
  # celery:
  #   build: ./celery

volumes:
  postgres:
  webpack_bundles:
  redis:
