version: '3'

services:

  prod:
    image: timvanmourik/giraffe-tools
    volumes:
      - .:/code
    command: bash bin/docker-prod-command.bash
    ports:
      - "8000:8000"
  web:
    build: .
    image: timvanmourik/giraffe-tools
    volumes:
      - .:/code
    command: bash bin/docker-command.bash
    ports:
      - "8000:8000"
