version: '3'

services:

  database:
    build: ./database
    volumes:
      # This saves the database to a persistent volume:
      - postgres:/var/lib/postgresql/data
      # You could also save it locally to the `database` directory...
      # - ./database:/var/lib/postgresql/data
      # if ever we want to initialise the database
      # - ./demo.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      #TODO only works without quotes here, not sure why
      - 5432   # database port
    environment:
      - POSTGRES_DB=giraffetools
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=giraffe
      - PGDATA=/tmp

  web:
    environment:
      - CHOKIDAR_USEPOLLING=true # for hot reloading on Windows
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - POSTGRES_DB=giraffetools
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=giraffe
    build: ./backend
    image: timvanmourik/giraffe-tools
    volumes:
      - ./backend:/code
      - webpack_bundles:/webpack
    command: ./bin/docker-command.bash
    ports:
      - "8000:8000"   # application server
      - "35729:35729"   # django live reload server
    depends_on:
      - database
      - frontend

  frontend:
    environment:
      - CHOKIDAR_USEPOLLING=true # for hot reloading on Windows
    build: ./frontend
    volumes:
      - ./frontend:/react
      - webpack_bundles:/bundles
    ports:
      - "3000:3000"    # database port
    command: ./bin/docker-command.bash


  # worker:
    # build: ./worker

  # coala is the 'linter', checking coding standard consistency
  # Before you commit, run 'docker-compose run coala' to automatically fix all
  # stylistic inconsistencies! :)
  coala:
    image: nemaniarjun/coala-docker-updated
    # image: coala/base
    command: coala
    working_dir: /code
    volumes:
      - .:/code
      - ./coala:/cache

volumes:
  postgres:
  webpack_bundles:
