version: '3'

services:
  web:
    environment:
      - CHOKIDAR_USEPOLLING=true # for hot reloading on Windows
    build: .
    image: timvanmourik/giraffe-tools
    volumes:
      - .:/code
    command: bash bin/docker-command.bash
    ports:
      - "8000:8000"   # application server
      - "3000:3000"   # webpack hot reload server
      - "35729:35729" # django live reload server
