# Generated by Django 2.1.5 on 2019-02-03 10:25

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import giraffe.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("id", models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name="ID")),
                ("created_on", models.DateTimeField(
                    db_index=True, default=giraffe.models.get_time)),
                ("modified_on", models.DateTimeField(
                    default=giraffe.models.get_time)),
                ("handle", models.CharField(db_index=True, max_length=255)),
                ("email", models.CharField(blank=True, db_index=True, max_length=255)),
                ("user", models.OneToOneField(blank=True, null=True,
                                              on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserAction",
            fields=[
                ("id", models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name="ID")),
                ("created_on", models.DateTimeField(
                    db_index=True, default=giraffe.models.get_time)),
                ("modified_on", models.DateTimeField(
                    default=giraffe.models.get_time)),
                ("action", models.CharField(choices=[
                 ("Login", "Login"), ("Logout", "Logout"), ("Commit", "Commit")], max_length=50)),
                ("ip_address", models.GenericIPAddressField(null=True)),
                ("location_data",
                 django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ("profile", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              related_name="actions", to="giraffe.Profile")),
                ("user", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                           related_name="actions", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
