apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: "{{ KUBE_CERT_AUTH_DATA }}"
    server: "{{ KUBE_SERVER }}"
  name: "{{ KUBE_CLUSTER }}"
contexts:
- context:
    cluster: "{{ KUBE_CLUSTER }}"
    user: "{{ KUBE_CLUSTER }}"
  name: "{{ KUBE_CLUSTER }}"
current-context: "{{ KUBE_CLUSTER }}"
kind: Config
preferences: {}
users:
- name: "{{ KUBE_CLUSTER }}"
  user:
    auth-provider:
      config:
        access-token: "{{ KUBE_ACCESS_TOKEN }}"
        cmd-args: config config-helper --format=json
        cmd-path: /google/google-cloud-sdk/bin/gcloud
        expiry: '2222-02-02T02:22:22Z'
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
