# Generated by Django 2.1.7 on 2019-04-23 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import giraffe.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('giraffe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=giraffe.models.get_time)),
                ('modified_on', models.DateTimeField(default=giraffe.models.get_time)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('user', models.ForeignKey(help_text='The projects of a user.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
