# Generated by Django 2.1.7 on 2019-05-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giraffe', '0002_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='name',
        ),
        migrations.AddField(
            model_name='project',
            name='repo_name',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='user_name',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
    ]
